import {
    busSeats
} from "./busSeats";

export const predefinedRoutes = [{
        id: "22223dkrre4lsk1111",
        slug: "rreewwx3",
        busName: "Hanif Enterprise",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "13-1-24",
        availableSeats: 40,
        price: 700,
        seats: busSeats
    },
    {
        id: "wr7kss3423dfjdfh",
        slug: "rreewwx4",
        busName: "SHOHAGH PARIBAHAN",
        description: "1, Hino-1j Series, AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '6:00 AM',
        arrival: '4:30 PM',
        date: "16-1-24",
        availableSeats: 40,
        price: 650,
        seats: busSeats
    },
    {
        id: "22223dkrre4lsk2112",
        slug: "rreewwx5",
        busName: "Soudia Coach Service",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '6:00 PM',
        arrival: '4:30 AM',
        date: "10-1-24",
        availableSeats: 40,
        price: 600,
        seats: busSeats
    },
    {
        id: "22223dkrre4lsk1141",
        slug: "rreewwx6",
        busName: "Royel Coach",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Comilla",
        startingPoint: "Comilla",
        endingPoint: "Dhaka",
        departure: '10:00 AM',
        arrival: '1:30 PM',
        date: "13-1-24",
        availableSeats: 40,
        price: 400,
        seats: busSeats
    },
    {
        id: "22223dkrrds4lsk1911",
        slug: "rreewwx7",
        busName: "Miami Enterprise",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Cox's Bazar",
        startingPoint: "Dhaka",
        endingPoint: "Cox's Bazar",
        departure: '8:00 PM',
        arrival: '6:30 AM',
        date: "27-1-24",
        availableSeats: 40,
        price: 1700,
        seats: busSeats
    },
    {
        id: "22223dwekrre4l4sk114431",
        slug: "rreewwx8",
        busName: "Green Line",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "13-1-24",
        availableSeats: 40,
        price: 1400,
        seats: busSeats
    },
    {
        id: "22223dkrre4lsk113",
        slug: "rreewwx9",
        busName: "Hanif Enterprise",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Cumilla - Chittagong",
        startingPoint: "Cumilla",
        endingPoint: "Chittagong",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "19-6-29",
        availableSeats: 40,
        price: 500,
        seats: busSeats
    },
    {
        id: "223dkrresafd4lsk1111",
        slug: "rreewwx10",
        busName: "Ena",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "13-2-24",
        availableSeats: 40,
        price: 700,
        seats: busSeats
    },
    {
        id: "22d223dkrre4lsk1111",
        slug: "rreewx11",
        busName: "Tisha Enterprise",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Rajshashi",
        startingPoint: "Dhaka",
        endingPoint: "Rajshashi",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "13-1-24",
        availableSeats: 40,
        price: 700,
        seats: busSeats
    },
    {
        id: "22223dkrre4lsk1111v",
        slug: "rreewwx12",
        busName: "Hanif Enterprise",
        description: "Hino, AK1J Super Plus Non AC",
        route: "Dhaka - Chittagong",
        startingPoint: "Dhaka",
        endingPoint: "Chittagong",
        departure: '8:00 AM',
        arrival: '3:30 PM',
        date: "13-1-24",
        availableSeats: 40,
        price: 700,
        seats: busSeats
    },

];